Repository Unithon-INU/2025_UNITHON_TEAM_4_FE, pull requests merged in 2025-06, with the labels that each got.

#13 [Design] 메인페이지 퍼블리싱
  package.json
  src/apis/client.ts
  src/apis/index.tsx
  src/apis/login.ts
  src/components/ui/Badge.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/pages/Festival/components/AppliedFilters.tsx
  src/pages/Festival/components/FeaturedFestivalSlider.tsx
  src/pages/Festival/components/FestivalGrid.tsx
  src/pages/Festival/components/FilterBar.tsx
  src/pages/Festival/components/PeriodSelcectorBar.tsx
  src/pages/Festival/components/SearchBar.tsx
  src/pages/Festival/festivals.tsx
  src/pages/Main/components/Card.tsx
  src/pages/Main/components/FooterSection.tsx
  src/pages/Main/components/Hero.tsx
  src/pages/Main/components/KeywordSection.tsx
  src/pages/Main/components/SeasonSection.tsx
  src/pages/Main/components/seasonalFestivals.ts
  src/pages/Main/index.tsx
  src/routes/router.tsx
  yarn.lock
Labels: design

#17 [feat] : 기본적인 로그인,회원가입 api 연동 완료
  src/apis/client.ts
  src/apis/login.ts
  src/apis/signup.ts
  src/pages/Auth/login.tsx
  src/pages/Auth/signup.tsx
  yarn.lock
Labels: feat

#19 [fix] 배포빌드시 tsc 오류 수정
  src/components/CommentSection/index.tsx
  src/pages/Auth/login.tsx
  src/pages/Auth/signup.tsx
  src/pages/Festival/components/Calendar.tsx
  src/pages/Festival/components/FilterBar.tsx
  src/pages/Festival/components/PeriodSelcectorBar.tsx
  src/pages/Festival/components/Popover.tsx
  src/pages/Festival/components/Select.tsx
  src/pages/Festival/constants.ts
  src/routes/routePath.ts
  src/routes/router.tsx
  vite.config.ts
Labels: bug

#26 [fix] 배포시 mixedcontent오류 proxy적용
  package.json
  src/apis/client.ts
  src/apis/login.ts
  src/apis/proxy.ts
  src/apis/signup.ts
  yarn.lock
Labels: bug

#28 [fix] console.log로 요청url decoding확인
  src/apis/proxy.ts
Labels: bug

#29 [fix] 루트로 proxy.ts이동
  api/proxy.ts
  tsconfig.app.json
Labels: bug

#36 [Feat] 축제 api 1차연동 완료
  api/proxy.ts
  api/tsconfig.json
  package.json
  src/App.tsx
  src/apis/client.ts
  src/apis/festival.ts
  src/hooks/useBottomObserver.ts
  src/hooks/useFestivalList.ts
  src/libraries/reactQuery/ReactQuerySetting.tsx
  src/libraries/reactQuery/queryKeys.ts
  src/pages/Festival/LoadingFestival.tsx
  src/pages/Festival/components/AppliedFilters.tsx
  src/pages/Festival/components/FeaturedFestivalSlider.tsx
  src/pages/Festival/components/FestivalGrid.tsx
  src/pages/Festival/components/FilterBar.tsx
  src/pages/Festival/components/SearchBar.tsx
  src/pages/Festival/components/Tabs.tsx
  src/pages/Festival/festivalperiod.tsx
  src/pages/Festival/festivals.tsx
  src/types/festival.d.ts
  vercel.json
  yarn.lock
Labels: feat

#38 [fix] 무한스크롤 조건 훅 축제갯수 8개로 정상화, 축제카드 렌더링 useCallback->useEffect로 변경
  src/hooks/useFestivalList.ts
  src/pages/Festival/components/FestivalGrid.tsx
Labels: bug

#40 [fix] proxy.ts에 쿼리 파라미터 조립로직 추가
  api/proxy.ts
Labels: bug

#42 [Feat] 마이페이지 내 게시물 api 연동 + 커뮤니티 페이지 api 연동
  src/apis/client.ts
  src/apis/createPost.ts
  src/apis/post.ts
  src/apis/posts.ts
  src/apis/users.ts
  src/pages/Auth/login.tsx
  src/pages/Community/components/CommentSection.tsx
  src/pages/Community/components/PostGrid.tsx
  src/pages/Community/create.tsx
  src/pages/Community/post.tsx
  src/pages/Mypage/index.tsx
  src/pages/Mypage/postModify.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
Labels: feat

#47 [fix] req.body를 fetch에 넘기는 대신, req객체 자체를 fetch의 body에 duplex: half와 함…
  api/proxy.ts
Labels: bug

#51 [feat] 401, 403에러시 /login으로 리다이렉팅
  package.json
  src/apis/client.ts
  src/i18n/locales/eng.json
  src/i18n/locales/jpn.json
  src/i18n/locales/kor.json
  yarn.lock
Labels: feat
